dist: bionic

language: php

php:
  - 7.4
  - 8.0

branches:
  only:
    - master
    - dev

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: php vendor/bin/phpunit --testsuite=Unit
