on:
  workflow_call:

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.2' ]

    services:
      navbar-mariadb:
        image: mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: password
          MYSQL_DATABASE: navbar
          MYSQL_PASSWORD: password
          MYSQL_USER: navbar
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP "${{ matrix.php-versions }}"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo_mysql

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Disable XDebug
        run: sudo phpdismod xdebug

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory permissions
        run: chmod -R 777 laravel/storage laravel/bootstrap/cache

      - name: Generate key
        run: php laravel/artisan key:generate

      - name: Migrate and Seed DB
        run: |
          php artisan migrate:fresh
          php artisan db:seed

      - name: Run PHPUnit tests
        run: |
          php -d zend_extension=xdebug.so -d xdebug.mode=coverage vendor/bin/phpunit \
          --no-coverage --coverage-text=php://stdout
